FROM postgres:17

# انسخ السكريبت لجوه الكونتينر
COPY init-postgres.sh /usr/local/bin/init-postgres.sh

# خلي السكريبت قابل للتنفيذ
RUN chmod +x /usr/local/bin/init-postgres.sh

# شغّل السكريبت كـ entrypoint بدل الرسمي
ENTRYPOINT ["/usr/local/bin/init-postgres.sh"]
